language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
python:
  - "2.7"
# command to install dependencies
install: "pip install -r dev-requirements.txt"
# command to run tests
script: py.test pyOCD/test